### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by tariqul-islam** [qubvel/segmentation_models.pytorch#216]
Hi, When I was running the tutorial on cars segmentation (CamVid), I got the following error:

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

Which is providing error while downloading the pre-trained network.

I could download the net manually using the browser (where it provided an error but I just bypassed it). 
and run the tutorial.

**Comment by phamquiluan** [comment]
same problem

**Comment by DaniilBoiko** [comment]
Same problem with all SE models. https://data.lip6.fr — from where all the SE pre-trained models in Cadene are downloaded from — has an expired certificate.
As suggested @AlxZed (https://github.com/Cadene/pretrained-models.pytorch/issues/193) you can do this:

`import ssl
ssl._create_default_https_context = ssl._create_unverified_context
`

**Comment by tommiekerssies** [comment]
Same problem, this should be fixed

**Comment by Progern** [comment]
As of today this issue still persists for Xception and Inception at least.

**Comment by seb2o** [comment]
this issue still exist (certificate of https://data.lip6.fr/ expired in 2022). I am not sure on how to resolve it, except if training and hosting weights somewhere else is an option
